name: Push (Stable)
concurrency:
  cancel-in-progress: true
  group: build-stable
on:
  push:
    branches:
      - stable
jobs:
  build_and_deploy:
    name: Test, Build & Deploy
    runs-on: ubuntu-latest
    environment:
      name: Live
      url: https://entrejourn.in/
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY  }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - run: npm ci
        name: Install

      - run: npm run lint
        name: Check linting
        continue-on-error: true # Temporary

      - run: npm run test:ci
        name: Run unit tests
        continue-on-error: true # Temporary

      - run: npm run build
        name: Build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: Deploy
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENTREJOURN_32FDF }}'
          projectId: entrejourn-32fdf
          channelId: live
