name: Update videos
concurrency:
  cancel-in-progress: true
  group: update-videos
on: workflow_dispatch
jobs:
  update_videos:
    name: Query videos and update videos.json
    runs-on: ubuntu-latest
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY  }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        
      - name: Install
        run: npm ci
        
      - name: Run script
        run: npm run update:videos

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'chore: update videos'
